name: Run Python Script

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        pip install beautifulsoup4
        pip install pandas
    - name: Run Fighters Python script
      run: python Scrapper/web_scrapper.py
    - name: Run UFC stat Python script
      run: python Scrapper/ufc_stats_scrapper.py
    - name: Add files to Git add and commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update Fighters files to the main branch"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: main
        github_token: ${{ secrets.OWN_GITHUB_TOKEN }}



