name: Run Python Script

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        pip install beautifulsoup4
        pip install pandas
    - name: Run Python script
      run: python Scrapper/web_scrapper.py
    - name: Add files to Git index
      run: git add .
    - name: Commit and push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.OWN_GITHUB_TOKEN }}
        branch: main
        directory: .
        message: Update files


